PR troubles
unhqly/RoR_TestGuru pull request #2
Opened 2023-05-24 16:28 UTC by unhqly

2023-05-24 17:00 UTC, BubuntuClu requested changes

2023-05-24 17:00 UTC, BubuntuClu commented on public/about/author.html
>      <h1>Author: Mikulin Mikhail, https://github.com/unhqly</h1>
тут должна быть ссылка, котоаря при клике на не еоткрывает ссылку в новом окне и ведет на твой гитхаб

2023-05-24 17:00 UTC, BubuntuClu commented on public/about.html
>      <h1>This is a Ruby on Rails tutorial from www.thinknetica.com</h1>
тут должна быть ссылка, котоаря при клике на не еоткрывает ссылку в новом окне и ведет на твой гитхаб

2023-05-24 17:00 UTC, BubuntuClu commented on public/about.html
>    <body>
вообще файлы страниц должны быть полностью новые в ПРе, у тебя же тут уже файлы есть и ты запушил изменения в этих файлах

2023-05-24 17:00 UTC, BubuntuClu commented on config/initializers/version.rb
> +TestGuru::Application::VERSIONS = "1.0.0"               #Lesson1
по документации стартовая версия приложения начинается с цифр 0.1.0

2023-05-24 19:48 UTC, unhqly commented on public/about.html
>    <body>
пришлось смержить предыдущий ПР с мастером, поэтому так. учту в следующих заданиях

2023-05-25 07:10 UTC, BubuntuClu commented on public/about.html
> +    <h1>This is a Ruby on Rails tutorial from <a href="https://www.thinknetica.com">Thinknetica</a></h1>
ссылки на внешние ресурсы должны открываться в новой влкадке, для этого есть доп опция для тэга а

2023-05-25 07:10 UTC, BubuntuClu commented on public/about/author.html
> +    <h1>Author: Mikulin Mikhail, <a href="https://github.com/unhqly">Github Profile</a></h1>
ссылки на внешние ресурсы должны открываться в новой влкадке, для этого есть доп опция для тэга а

2023-05-29 08:44 UTC, merged