Lesson2
unhqly/RoR_TestGuru pull request #3
Opened 2023-06-06 22:13 UTC by unhqly

2023-06-07 06:55 UTC, BubuntuClu requested changes

2023-06-07 06:55 UTC, BubuntuClu commented on db/migrate/20230606204501_create_questions.rb
> +      t.integer :test_id
это должно быть внешним ключом. нужно использовать синтаксис `t.references`

2023-06-07 06:55 UTC, BubuntuClu commented on db/migrate/20230606205412_create_answers.rb
> +      t.integer :question_id
внешний ключ

2023-06-07 06:55 UTC, BubuntuClu commented on db/migrate/20230606210048_create_results.rb
> +    create_table :results do |t|
за что отвечает эта таблица? зачем в ней столько всего еще и с дубликатом информации?

2023-06-07 06:55 UTC, BubuntuClu commented on db/migrate/20230606211923_create_result_tests.rb
> +    create_table :result_tests do |t|
чем это отличается от таблицы `results`?

2023-06-07 06:55 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "level", default: 0
нужен внешний ключ к категориям

2023-06-07 12:38 UTC, unhqly commented on db/migrate/20230606210048_create_results.rb
> +    create_table :results do |t|
здесь информация о каждом ответе каждого пользователя в каждом тесте. может быть полезно хранить такую информацию

2023-06-07 12:39 UTC, unhqly commented on db/migrate/20230606211923_create_result_tests.rb
> +    create_table :result_tests do |t|
здесь информация о прохождении пользователем теста. в results будут храниться результаты по ответам, в resut_tests результаты по тестам

2023-06-07 17:39 UTC, BubuntuClu commented on db/migrate/20230606210048_create_results.rb
> +    create_table :results do |t|
понял. в рамках этого курса это не будет использоваться, тебе надо будет придумать функционал для этого самому

2023-06-07 17:43 UTC, BubuntuClu requested changes

2023-06-07 17:43 UTC, BubuntuClu commented on db/migrate/20230603085229_create_tests.rb
> +      t.references :category, foreign_key: {to_table: :categories}
думаешь это корректно что таблица к которое ты создаешь внешний ключ еще не существует на этом этапе?

sqlite несильно на внешние ключи смотрит. при переходе на серьезные БД, ты будешь получать оишбку

2023-06-07 17:43 UTC, BubuntuClu commented on db/migrate/20230603085229_create_tests.rb
> +      t.integer :level, :default => 0
`default: 0`

2023-06-07 17:43 UTC, BubuntuClu commented on db/migrate/20230606205412_create_answers.rb
> +      t.boolean :positive, null: false, :default => false
`default: false`.
придерживайся одного стиля написания кода

2023-06-07 17:43 UTC, BubuntuClu commented on db/migrate/20230603085229_create_tests.rb
>  class CreateTests < ActiveRecord::Migration[7.0]
оооо, вот тут приплыли.
gem "rails", "~> 7.0.4", ">= 7.0.4.3" ты используешь 7ую рельсу. она сильно отличается от того что рассказывают в уроках.

в первом задании было написано что надо использовать 6ю версию.
надо переделать проект на 6ой рельсе

2023-06-14 16:09 UTC, unhqly commented on db/migrate/20230606205412_create_answers.rb
> +      t.boolean :positive, null: false, :default => false
типы данных отличаются же. в ответах boolean, в тестах integer. все равно поменять?

2023-06-14 17:29 UTC, BubuntuClu commented on db/migrate/20230606205412_create_answers.rb
> +      t.boolean :positive, null: false, :default => false
а причем тут тип данных? я про то что ты используешь два вида записи параметров,  `null: false` и `:default => false`. второй вариант записи устареший вид

2023-08-28 19:48 UTC, merged