Lesson3
unhqly/RoR_TestGuru pull request #4
Opened 2023-08-30 12:30 UTC by unhqly

2023-08-30 18:48 UTC, BubuntuClu requested changes

2023-08-30 18:48 UTC, BubuntuClu commented on app/models/user.rb
> +    .joins('JOIN users ON users.id = result_tests.user_id')
это лишнее, у тебя есть user_id в таблице прохождений. тебе не нужно никакое поле из таблицы пользователя => таблицу пользователей можно не джойнить

2023-08-30 18:48 UTC, BubuntuClu commented on db/seeds.rb
> +Test.create(title: 'SQL', level: 0, category_id: 1)
`category_id: 1` это хардкод, который сломается если не будет в твоей таблицы категорий строки с таким ID. надо это исправить. сохраняй созданные объекты в переменные и используй их для создания динамического подставления значений в нужные поля

у тебя ООП язык, используй его возможности)

справделиво ко всем строкам ниже

2023-08-30 18:48 UTC, BubuntuClu commented on log/development.log
>  Completed 200 OK in 44ms (Views: 24.9ms | ActiveRecord: 0.0ms | Allocations: 3457)
этот файл надо поместить в `gitignor`. в репоизторий не надо помещать никакие логи

2023-08-30 18:48 UTC, BubuntuClu commented on db/seeds.rb
> +Result.create(user_id: 1, test_id: 1, question_id: 1, answer_id: 2, answer_positive: false)
в курсе программы такая таблица не будет задействована, тебе самому придеться придумывать для нее функциональность

2023-08-31 14:49 UTC, unhqly commented on app/models/user.rb
> +    .joins('JOIN users ON users.id = result_tests.user_id')
да, что-то я затроил

2023-09-11 20:00 UTC, merged